LinkLuaModifier("modifier_respawn_bonus","scripts/vscripts/modifiers/modifier_respawn_bonus.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_disconnected","scripts/vscripts/modifiers/modifier_disconnected.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_provides_vision","scripts/vscripts/modifiers/modifier_provides_vision.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_fighting_area_poison","scripts/vscripts/modifiers/modifier_fighting_area_poison.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_bom_truesight","scripts/vscripts/modifiers/modifier_bom_truesight.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_disconnect_detection","scripts/vscripts/modifiers/modifier_disconnect_detection.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_waiting_for_precache","scripts/vscripts/modifiers/modifier_waiting_for_precache.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_daytime_vision_range_bonus","scripts/vscripts/modifiers/modifier_daytime_vision_range_bonus.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_fearless_brave","scripts/vscripts/modifiers/modifier_fearless_brave.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_shame_of_deserter","scripts/vscripts/modifiers/modifier_shame_of_deserter.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_shame_of_deserter_tooltip","scripts/vscripts/modifiers/modifier_shame_of_deserter_tooltip.lua",LUA_MODIFIER_MOTION_NONE)

